
export const scalename = 'scale'
export const rotatename = 'rotate'
export const translatename = 'translate'
export const pixelunit = 'px'
export const degreesunit = 'deg'
export const colourhighlight = '#C8C8FF'
export const dragicon = 'ns-resize'
export const defaulticon = 'default'
export const inputtimename = 'inputtime'
export const inputopacityname = 'inputopacity'
export const loadingscreentime = '800ms'